name: "Build Server"
on: push
jobs:
  buildServer:
    name: "Build Backend Job"
    runs-on: ubuntu-18.04

    services:
      mongo:
        image: "mongo:4.4.4"
        ports: 
          - 27017:27017
        options: --health-cmd="echo 'db.runCommand(\"ping\").ok' | mongo localhost:27017/test --quiet" --health-timeout="1s" --health-interval="1s" --health-retries="15"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup node 14 LTS"
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: "Install node modules"
        run: npm ci
        working-directory: server

      - name: "Run the linter"
        run: npm run lint
        working-directory: server

      - name: "Run the backend tests"
        run: npm run test
        working-directory: server
          
